"""
AutoMixAI – Hainsworth Dataset Downloader
==========================================
Downloads the Hainsworth beat-tracking dataset using mirdata.

The Hainsworth dataset contains 222 audio tracks with **human-annotated
beat timestamps** — far more accurate labels than the pseudo-labels
generated by librosa's beat tracker used in the Ballroom/FMA pipeline.

Requirements:
    pip install mirdata

Approximate size: ~1.8 GB audio + annotations

Usage:
    python download_hainsworth.py                        # download to default location
    python download_hainsworth.py --dest D:/Datasets     # custom destination
"""

import argparse
import sys
from pathlib import Path


# ── CLI ───────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Download Hainsworth beat dataset")
parser.add_argument(
    "--dest",
    type=str,
    default=str(Path(__file__).parent / "Datasets" / "hainsworth"),
    help="Destination directory (default: ./Datasets/hainsworth)",
)
parser.add_argument(
    "--validate",
    action="store_true",
    help="Run checksum validation after download",
)
args = parser.parse_args()

dest = Path(args.dest)
dest.mkdir(parents=True, exist_ok=True)
print(f"[AutoMixAI] Hainsworth download → {dest}\n")


# ── Check mirdata ─────────────────────────────────────────────────────────────
try:
    import mirdata
except ImportError:
    print("ERROR: mirdata not installed.")
    print("Run: pip install mirdata")
    sys.exit(1)


# ── Initialize & download ─────────────────────────────────────────────────────
print("[1/4] Initialising dataset...")
dataset = mirdata.initialize("hainsworth", data_home=str(dest))

print("[2/4] Downloading (~1.8 GB, may take several minutes)...")
dataset.download()

if args.validate:
    print("[3/4] Validating checksums...")
    dataset.validate()
else:
    print("[3/4] Skipping checksum validation (pass --validate to enable).")


# ── Verify & summary ──────────────────────────────────────────────────────────
print("[4/4] Verifying tracks...\n")
track_ids = dataset.track_ids
print(f"  Total tracks : {len(track_ids)}")

ok, missing, no_beats = 0, 0, 0
beat_counts = []

for tid in track_ids:
    track = dataset.track(tid)
    try:
        audio_path = track.audio_path
        if not Path(audio_path).exists():
            missing += 1
            continue
        beats = track.beats
        if beats is None or len(beats.times) == 0:
            no_beats += 1
            continue
        beat_counts.append(len(beats.times))
        ok += 1
    except Exception as e:
        missing += 1

print(f"  Audio found  : {ok}")
print(f"  Missing audio: {missing}")
print(f"  No beat ann. : {no_beats}")
if beat_counts:
    import statistics
    print(f"  Avg beats/track: {statistics.mean(beat_counts):.0f}")

# ── Sample inspection ─────────────────────────────────────────────────────────
print("\n── Sample track (first) ──────────────────────────────────────")
try:
    t0 = dataset.track(track_ids[0])
    beats = t0.beats
    print(f"  Track ID   : {t0.track_id}")
    print(f"  Audio path : {t0.audio_path}")
    if beats is not None:
        print(f"  Beat times : {beats.times[:10].tolist()} ... ({len(beats.times)} total)")
        print(f"  Beat confs : {beats.confidences[:5].tolist() if beats.confidences is not None else 'N/A'}")
except Exception as e:
    print(f"  Could not load sample: {e}")

print(f"\n✅  Hainsworth dataset ready at: {dest}")
print("\n── Next steps ────────────────────────────────────────────────")
print("  Upload the 'hainsworth' folder as a Kaggle Dataset and")
print("  use kaggle/AutoMixAI_Training_v2.ipynb to train with")
print("  REAL beat annotations (much better than pseudo-labels!).")