"""
AutoMixAI – Model Training Pipeline

Handles loading labelled data, optional pseudo-label generation for
unlabeled tracks, training the beat-detection ANN, and saving the
trained model to disk.
"""

import csv
from pathlib import Path

import numpy as np
import librosa

from app.model.ann_model import build_model
from app.services.audio_loader import load_audio
from app.services.feature_extractor import extract_features
from app.utils.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)


# ── Data helpers ──────────────────────────────────────────────────────

def _load_beat_annotations(label_path: str, n_frames: int, sr: int) -> np.ndarray:
    """
    Convert a CSV of beat timestamps into a binary label vector.

    The CSV should contain one beat timestamp (in seconds) per row in
    the first column.  Each timestamp is mapped to the nearest analysis
    frame, and that frame receives label ``1``; all others are ``0``.

    Args:
        label_path: Path to the beat-annotation CSV.
        n_frames:   Total number of analysis frames.
        sr:         Sample rate used during feature extraction.

    Returns:
        Binary label array of shape ``(n_frames,)``.
    """
    labels = np.zeros(n_frames, dtype=np.float32)

    with open(label_path, newline="") as fh:
        reader = csv.reader(fh)
        for row in reader:
            if not row:
                continue
            beat_time = float(row[0])
            frame_idx = librosa.time_to_frames(
                beat_time, sr=sr, hop_length=settings.hop_length
            )
            if 0 <= frame_idx < n_frames:
                labels[frame_idx] = 1.0

    logger.info(
        "Loaded %d beat annotations from %s",
        int(labels.sum()),
        label_path,
    )
    return labels


def generate_pseudo_labels(audio_path: str, sr: int | None = None) -> np.ndarray:
    """
    Generate pseudo beat labels for an unlabeled audio file using
    librosa's built-in beat tracker.

    This allows expanding the training set when ground-truth
    annotations are unavailable.

    Args:
        audio_path: Path to the audio file.
        sr:         Sample rate (defaults to ``settings.sample_rate``).

    Returns:
        Binary label array of shape ``(n_frames,)``.
    """
    sr = sr or settings.sample_rate
    y, sr = load_audio(audio_path, sr=sr)

    # Use librosa beat tracker to generate pseudo labels
    _, beat_frames = librosa.beat.beat_track(
        y=y, sr=sr, hop_length=settings.hop_length
    )

    total_frames = 1 + len(y) // settings.hop_length
    labels = np.zeros(total_frames, dtype=np.float32)
    for frame in beat_frames:
        if 0 <= frame < total_frames:
            labels[frame] = 1.0

    logger.info(
        "Generated %d pseudo-labels for %s",
        int(labels.sum()),
        audio_path,
    )
    return labels


# ── Data loading ──────────────────────────────────────────────────────

def load_training_data(
    data_dir: str | Path | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Load training data in order of preference:

    1. **Pre-processed** ``data/processed/X.npy`` + ``y.npy``
       (generated by ``python -m app.data.prepare_data``).
    2. **Raw audio** from ``data/raw/*.wav`` with matching annotation
       CSVs in ``data/labels/`` (pseudo-labels generated if missing).

    Args:
        data_dir: Override for the raw data directory.

    Returns:
        Tuple ``(X, y)`` ready for model training.
    """
    # ── 1. Try pre-processed .npy files first ─────────────────────────
    processed_X = settings.processed_data_dir / "X.npy"
    processed_y = settings.processed_data_dir / "y.npy"

    if processed_X.exists() and processed_y.exists():
        logger.info("Loading pre-processed data from %s", settings.processed_data_dir)
        X = np.load(str(processed_X))
        y_labels = np.load(str(processed_y))
        logger.info("Loaded processed data: X=%s, y=%s", X.shape, y_labels.shape)
        return X, y_labels

    # ── 2. Fall back to raw audio files ──────────────────────────────
    logger.info("No pre-processed data found — loading from raw audio")

    raw_dir = Path(data_dir or settings.raw_data_dir)
    labels_dir = settings.labels_dir

    all_features: list[np.ndarray] = []
    all_labels: list[np.ndarray] = []

    audio_files = sorted(raw_dir.glob("*.wav"))
    if not audio_files:
        logger.warning("No .wav files found in %s", raw_dir)

    for audio_path in audio_files:
        logger.info("Processing training file: %s", audio_path.name)

        y_audio, sr = load_audio(str(audio_path))
        features = extract_features(y_audio, sr)
        n_frames = features.shape[0]

        # Look for a matching label file
        label_path = labels_dir / audio_path.with_suffix(".csv").name
        if label_path.exists():
            labels = _load_beat_annotations(str(label_path), n_frames, sr)
        else:
            logger.info(
                "No label file for %s — generating pseudo-labels",
                audio_path.name,
            )
            labels = generate_pseudo_labels(str(audio_path), sr)[:n_frames]

        all_features.append(features)
        all_labels.append(labels)

    if not all_features:
        raise ValueError(
            "No training data found. Either:\n"
            "  1. Run 'python -m app.data.prepare_data' to process Ballroom + FMA datasets, or\n"
            "  2. Place .wav files in data/raw/"
        )

    X = np.vstack(all_features)
    y_labels = np.concatenate(all_labels)
    logger.info("Training data assembled: X=%s, y=%s", X.shape, y_labels.shape)
    return X, y_labels


# ── Training ──────────────────────────────────────────────────────────

def train_model(
    data_dir: str | Path | None = None,
    model_save_path: str | Path | None = None,
    epochs: int | None = None,
    batch_size: int | None = None,
) -> None:
    """
    End-to-end training pipeline: load data → build model → fit → save.

    Args:
        data_dir:        Override for the raw data directory.
        model_save_path: Where to save the ``.h5`` model file.
        epochs:          Number of training epochs.
        batch_size:      Mini-batch size.
    """
    model_save_path = Path(model_save_path or settings.model_path)
    epochs = epochs or settings.training_epochs
    batch_size = batch_size or settings.training_batch_size

    logger.info("=== Starting model training ===")

    X, y_labels = load_training_data(data_dir)

    model = build_model(input_dim=X.shape[1])

    model.fit(
        X,
        y_labels,
        epochs=epochs,
        batch_size=batch_size,
        validation_split=0.2,
        verbose=2,
    )

    model_save_path.parent.mkdir(parents=True, exist_ok=True)
    model.save(str(model_save_path))
    logger.info("Model saved to %s", model_save_path)


# ── CLI entry point ──────────────────────────────────────────────────

if __name__ == "__main__":
    train_model()
